import 'package:powersync/powersync.dart';

const schema = Schema(([
  Table('users', [
    Column.text('id'),
    Column.text('nama'),
    Column.text('dob'),
    Column.text('keterangan'),
    Column.text('status'),
    Column.text('masuk'),
    Column.text('createdAt'),
  ], indexes: [
    // Index to allow efficient lookup within a list
    Index('customer', [IndexedColumn('id')]),
    Index('due_payment', [IndexedColumn('id')]),
    Index('expenses', [IndexedColumn('id')]),
    Index('inventory', [IndexedColumn('id')])
  ]),
  Table('customer', [
    Column.text('nama'),
    Column.text('phone'),
    Column.text('ktp'),
    Column.text('dob'),
    Column.text('keterangan'),
    Column.integer('status'),
    Column.text('masuk'),
    Column.text('user'),
    Column.text('createdAt'),
  ]),
  Table('due_payment', [
    Column.text('name'),
    Column.text('invoice'),
    Column.text('itemName'),
    Column.integer('itemAmount'),
    Column.integer('amount'),
    Column.text('status'),
    Column.text('note'),
    Column.text('dateIn'),
    Column.text('dueDate'),
    Column.text('createdAt'),
    Column.text('user'),
  ]),
  Table('due_payment', [
    Column.text('name'),
    Column.text('invoice'),
    Column.text('itemName'),
    Column.integer('itemAmount'),
    Column.integer('amount'),
    Column.text('status'),
    Column.text('note'),
    Column.text('dateIn'),
    Column.text('dueDate'),
    Column.text('createdAt'),
    Column.text('user'),
  ]),
  Table('expenses', [
    Column.text('title'),
    Column.text('note'),
    Column.integer('amount'),
    Column.text('createdAt'),
    Column.text('user'),
  ]),
  Table('inventory', [
    Column.text('nama'),
    Column.text('code'),
    Column.text('deskripsi'),
    Column.integer('jumlahBarang'),
    Column.integer('quantity'),
    Column.text('ukuran'),
    Column.integer('hargaDasar'),
    Column.real('hargaJualPersen'),
    Column.real('diskonPersen'),
    Column.integer('isHargaJualPersen'),
    Column.text('barangMasuk'),
    Column.text('barangKeluar'),
    Column.text('createdAt'),
    Column.text('user'),
  ]),
  Table('presense', [
    Column.text('user'),
    Column.text('status'),
    Column.text('note'),
    Column.text('path'),
    Column.real('long'),
    Column.real('lat'),
    Column.text('belong'),
  ])
]));
